# Generated by Django 6.0.5 on 2026-05-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('chatbot_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('meeting_users', models.ForeignKey(db_column='meeting_users_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingusers')),
            ],
            options={
                'db_table': 'chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot')),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
    ]
