# Generated by Django 6.0.5 on 2026-05-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('meeting_at', models.DateTimeField()),
                ('meeting_document', models.TextField(blank=True, null=True)),
                ('is_meeting', models.BooleanField(default=False)),
                ('meeting_users', models.ForeignKey(db_column='meeting_users_id', on_delete=django.db.models.deletion.PROTECT, to='projects.projectusers')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_agendas',
            },
        ),
        migrations.CreateModel(
            name='MeetingPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField()),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_preparation',
            },
        ),
        migrations.CreateModel(
            name='MeetingUsers',
            fields=[
                ('meeting_users_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'meeting_users',
            },
        ),
        migrations.CreateModel(
            name='MeetingTask',
            fields=[
                ('meeting_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('meeting_users', models.ForeignKey(db_column='meeting_users_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingusers')),
            ],
            options={
                'db_table': 'meeting_task',
            },
        ),
        migrations.CreateModel(
            name='OuterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'db_table': 'outer_document',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_path', models.TextField(blank=True, null=True)),
                ('record_row_text', models.TextField(blank=True, null=True)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.AddField(
            model_name='meetingusers',
            name='record',
            field=models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.record'),
        ),
    ]
