# Generated by Django 6.0.4 on 2026-06-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
