# Generated by Django 6.0.5 on 2026-05-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=90)),
                ('work', models.CharField(max_length=150)),
                ('password', models.CharField(default='abc123', max_length=255)),
                ('account_status', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('account_id', models.CharField(blank=True, db_column='account_Id', max_length=255, null=True)),
                ('role', models.CharField(default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dept', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.PROTECT, to='users.dept')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, to='users.rank')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
